[package]
name = "mysql-pulse"
version = "0.1.0"
authors = ["Jason Stelzer <mental@neverlight.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "*"
rust-ini = "0.15"
clap = "3.0.0-beta.1"